name: Setup CI
on:
  repository_dispatch:
    types: [setup]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          command: "setup"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
