name: Setup CI
on:
  repository_dispatch:
    types: [setup]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@master
        with:
          command: "setup"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
