name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [static-site]
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - ".upptimerc.yml"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
