name: Updates CI
on:
  schedule:
    - cron: "0 3 * * *"
  repository_dispatch:
    types: [updates]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
